version: "3.7"

services:
        app:
                container_name: myapp
                build:
                        context: .
                        target: develop
                ports:
                        - 3000:3000
                volumes:
                        - ./src:/home/node/app
                        - nodemodules:/home/node/app/node_modules
                networks:
                        - frontend
                        - backend

volumes:
        nodemodules:

networks:
        frontend:
        backend:
